import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../models/family_member.dart';
import '../models/family.dart';
import '../models/todo_item.dart';
import '../models/event.dart';
import '../models/memory.dart';
import '../models/transaction.dart';
import '../models/calendar_group.dart';
import '../models/chat_message.dart';
import '../models/memo.dart';
import '../models/memo_category.dart';

/// 데모 가족 구성원 (4명)
final demoMembersProvider = Provider<List<FamilyMember>>((ref) {
  return [
    FamilyMember(
      id: 'member1',
      familyId: 'family1',
      name: '엄마',
      email: 'mom@family.com',
      color: '#FFCBA4',
      role: 'admin',
      createdAt: DateTime.now(),
    ),
    FamilyMember(
      id: 'member2',
      familyId: 'family1',
      name: '아빠',
      email: 'dad@family.com',
      color: '#98D8C8',
      role: 'member',
      createdAt: DateTime.now(),
    ),
    FamilyMember(
      id: 'member3',
      familyId: 'family1',
      name: '큰딸',
      email: 'daughter@family.com',
      color: '#C9B1FF',
      role: 'member',
      createdAt: DateTime.now(),
    ),
    FamilyMember(
      id: 'member4',
      familyId: 'family1',
      name: '아들',
      email: 'son@family.com',
      color: '#9AD0EC',
      role: 'member',
      createdAt: DateTime.now(),
    ),
  ];
});

/// 데모 가족
final demoFamilyProvider = Provider<FamilyGroup>((ref) {
  return FamilyGroup(
    id: 'family1',
    name: '행복한 우리집',
    inviteCode: 'HAPPY1',
    createdAt: DateTime.now(),
  );
});

/// 데모 캘린더 그룹 (3개: 개인, 가족, 친구모임)
final demoCalendarGroupsProvider = Provider<List<CalendarGroup>>((ref) {
  final now = DateTime.now();
  return [
    CalendarGroup(
      id: 'cal_personal',
      name: '내 일정',
      type: CalendarGroupType.personal,
      color: '#7C83FD',
      memberIds: ['member1'],
      ownerId: 'member1',
      isDefault: true,
      createdAt: now,
    ),
    CalendarGroup(
      id: 'cal_family',
      name: '가족',
      type: CalendarGroupType.family,
      color: '#FF9F43',
      memberIds: ['member1', 'member2', 'member3', 'member4'],
      ownerId: 'member1',
      isDefault: false,
      createdAt: now,
    ),
    CalendarGroup(
      id: 'cal_friends',
      name: '친구모임',
      type: CalendarGroupType.friends,
      color: '#A55EEA',
      memberIds: ['member1', 'friend1', 'friend2'],
      ownerId: 'member1',
      isDefault: false,
      createdAt: now,
    ),
  ];
});

/// 데모 할일 (15개+)
final demoTodosProvider = Provider<List<TodoItem>>((ref) {
  final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);
  
  return [
    // 오늘 할일 - 긴급
    TodoItem(
      id: 'todo1',
      familyId: 'family1',
      title: '장보기 - 우유, 계란, 빵, 과일',
      note: '마트 세일 확인하기. 쿠폰 챙기기!',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today,
      priority: 2,
      createdAt: now.subtract(const Duration(hours: 2)),
      createdBy: 'member1',
    ),
    // 시간이 있는 할일 (Day View 테스트용)
    TodoItem(
      id: 'todo_timed1',
      familyId: 'family1',
      title: '아이 학원 픽업',
      note: '영어 학원 앞에서 대기',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today,
      priority: 2,
      createdAt: now.subtract(const Duration(hours: 1)),
      createdBy: 'member1',
      hasTime: true,
      startTime: DateTime(today.year, today.month, today.day, 16, 30),
      endTime: DateTime(today.year, today.month, today.day, 17, 0),
    ),
    TodoItem(
      id: 'todo_timed2',
      familyId: 'family1',
      title: '저녁 식사 준비',
      note: '오늘 메뉴: 된장찌개',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today,
      priority: 1,
      createdAt: now.subtract(const Duration(hours: 1)),
      createdBy: 'member1',
      hasTime: true,
      startTime: DateTime(today.year, today.month, today.day, 18, 0),
      endTime: DateTime(today.year, today.month, today.day, 19, 0),
    ),
    TodoItem(
      id: 'todo2',
      familyId: 'family1',
      title: '거실 청소하기',
      note: '진공청소기 돌리고 먼지 닦기',
      assigneeId: 'member3',
      isCompleted: false,
      dueDate: today,
      priority: 1,
      createdAt: now.subtract(const Duration(hours: 3)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo3',
      familyId: 'family1',
      title: '택배 수령',
      note: '오후 2시 이후 도착 예정 (롯데택배)',
      assigneeId: 'member2',
      isCompleted: true,
      dueDate: today,
      priority: 1,
      createdAt: now.subtract(const Duration(days: 1)),
      createdBy: 'member2',
    ),
    TodoItem(
      id: 'todo4',
      familyId: 'family1',
      title: '숙제하기 - 수학 문제집',
      note: '3단원 복습문제 풀기',
      assigneeId: 'member4',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 1)),
      priority: 2,
      createdAt: now.subtract(const Duration(hours: 5)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo5',
      familyId: 'family1',
      title: '병원 예약 확인',
      note: '내과 정기검진 - 오전 10시',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 2)),
      priority: 2,
      createdAt: now.subtract(const Duration(days: 3)),
      createdBy: 'member1',
    ),
    // 일상적인 할일
    TodoItem(
      id: 'todo6',
      familyId: 'family1',
      title: '세탁기 돌리기',
      assigneeId: 'member1',
      isCompleted: true,
      dueDate: today,
      priority: 0,
      createdAt: now.subtract(const Duration(hours: 6)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo7',
      familyId: 'family1',
      title: '식물에 물주기',
      note: '거실 화분 3개, 베란다 화분 2개',
      assigneeId: 'member3',
      isCompleted: false,
      dueDate: today,
      priority: 0,
      createdAt: now.subtract(const Duration(days: 2)),
      createdBy: 'member3',
    ),
    TodoItem(
      id: 'todo8',
      familyId: 'family1',
      title: '자동차 세차하기',
      assigneeId: 'member2',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 3)),
      priority: 0,
      createdAt: now.subtract(const Duration(days: 1)),
      createdBy: 'member2',
    ),
    TodoItem(
      id: 'todo9',
      familyId: 'family1',
      title: '피아노 연습 1시간',
      note: '발표회 준비곡 연습',
      assigneeId: 'member3',
      isCompleted: false,
      dueDate: today,
      priority: 1,
      repeatType: 'daily',
      createdAt: now.subtract(const Duration(days: 7)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo10',
      familyId: 'family1',
      title: '영어 단어 외우기',
      note: 'Day 15 ~ Day 20',
      assigneeId: 'member4',
      isCompleted: true,
      dueDate: today,
      priority: 1,
      createdAt: now.subtract(const Duration(hours: 8)),
      createdBy: 'member4',
    ),
    // 이번 주 할일
    TodoItem(
      id: 'todo11',
      familyId: 'family1',
      title: '공과금 납부',
      note: '전기세, 가스비, 수도세',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 4)),
      priority: 2,
      repeatType: 'monthly',
      createdAt: now.subtract(const Duration(days: 5)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo12',
      familyId: 'family1',
      title: '부모님 전화드리기',
      assigneeId: 'member2',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 1)),
      priority: 1,
      repeatType: 'weekly',
      createdAt: now.subtract(const Duration(days: 7)),
      createdBy: 'member2',
    ),
    TodoItem(
      id: 'todo13',
      familyId: 'family1',
      title: '분리수거 내놓기',
      assigneeId: 'member4',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 2)),
      priority: 1,
      repeatType: 'weekly',
      createdAt: now.subtract(const Duration(days: 14)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo14',
      familyId: 'family1',
      title: '생일 선물 준비 - 할머니',
      note: '건강식품 or 따뜻한 옷',
      assigneeId: 'member1',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 5)),
      priority: 2,
      createdAt: now.subtract(const Duration(days: 3)),
      createdBy: 'member1',
    ),
    TodoItem(
      id: 'todo15',
      familyId: 'family1',
      title: '도서관 책 반납',
      note: '3권 - 연체료 주의!',
      assigneeId: 'member3',
      isCompleted: false,
      dueDate: today.add(const Duration(days: 1)),
      priority: 2,
      createdAt: now.subtract(const Duration(days: 10)),
      createdBy: 'member3',
    ),
    TodoItem(
      id: 'todo16',
      familyId: 'family1',
      title: '운동하기 (헬스장)',
      assigneeId: 'member2',
      isCompleted: true,
      dueDate: today,
      priority: 1,
      repeatType: 'daily',
      createdAt: now.subtract(const Duration(days: 30)),
      createdBy: 'member2',
    ),
  ];
});

/// 데모 이벤트 (20개+) - 개인/공유 일정 포함
final demoEventsProvider = Provider<List<Event>>((ref) {
  final now = DateTime.now();
  final today = DateTime(now.year, now.month, now.day);
  
  return [
    // === 개인 일정 ===
    Event(
      id: 'event_p1',
      familyId: 'family1',
      title: '치과 정기검진',
      description: '스케일링 예약',
      startAt: today.add(const Duration(days: 1, hours: 10)),
      endAt: today.add(const Duration(days: 1, hours: 11)),
      participants: ['member1'],
      location: '서울치과의원',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 7)),
    ),
    Event(
      id: 'event_p2',
      familyId: 'family1',
      title: '미용실 예약',
      startAt: today.add(const Duration(days: 3, hours: 14)),
      endAt: today.add(const Duration(days: 3, hours: 16)),
      participants: ['member1'],
      location: '헤어살롱 강남점',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 2)),
    ),
    Event(
      id: 'event_p3',
      familyId: 'family1',
      title: '요가 수업',
      startAt: today.add(const Duration(hours: 7)),
      endAt: today.add(const Duration(hours: 8)),
      participants: ['member1'],
      location: '요가스튜디오',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 14)),
    ),
    Event(
      id: 'event_p4',
      familyId: 'family1',
      title: '회사 미팅',
      description: '분기 실적 보고',
      startAt: today.add(const Duration(days: 2, hours: 14)),
      endAt: today.add(const Duration(days: 2, hours: 16)),
      participants: ['member2'],
      location: '본사 회의실',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 5)),
    ),
    
    // === 가족 공유 일정 ===
    Event(
      id: 'event_f1',
      familyId: 'family1',
      title: '가족 저녁 외식',
      description: '아빠 생일 축하 🎂',
      startAt: today.add(const Duration(days: 2, hours: 18)),
      endAt: today.add(const Duration(days: 2, hours: 21)),
      participants: ['member1', 'member2', 'member3', 'member4'],
      location: '강남 이탈리안 레스토랑',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 10)),
    ),
    Event(
      id: 'event_f2',
      familyId: 'family1',
      title: '딸 피아노 발표회',
      description: '쇼팽 녹턴 연주',
      startAt: today.add(const Duration(days: 5, hours: 14)),
      endAt: today.add(const Duration(days: 5, hours: 16)),
      participants: ['member1', 'member2', 'member3'],
      location: '음악학원 대강당',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 20)),
    ),
    Event(
      id: 'event_f3',
      familyId: 'family1',
      title: '주말 등산',
      description: '북한산 백운대 코스',
      startAt: today.add(const Duration(days: 6, hours: 7)),
      endAt: today.add(const Duration(days: 6, hours: 15)),
      participants: ['member2', 'member4'],
      location: '북한산 국립공원',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 3)),
    ),
    Event(
      id: 'event_f4',
      familyId: 'family1',
      title: '할머니 생신',
      description: '선물 준비 완료',
      startAt: today.add(const Duration(days: 8)),
      endAt: today.add(const Duration(days: 8)),
      isAllDay: true,
      participants: ['member1', 'member2', 'member3', 'member4'],
      location: '할머니 댁',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 30)),
    ),
    Event(
      id: 'event_f5',
      familyId: 'family1',
      title: '아들 축구 경기',
      startAt: today.add(const Duration(days: 4, hours: 10)),
      endAt: today.add(const Duration(days: 4, hours: 12)),
      participants: ['member2', 'member4'],
      location: '학교 운동장',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 7)),
    ),
    Event(
      id: 'event_f6',
      familyId: 'family1',
      title: '가족 영화 관람',
      description: '새로 나온 애니메이션',
      startAt: today.add(const Duration(days: 7, hours: 15)),
      endAt: today.add(const Duration(days: 7, hours: 18)),
      participants: ['member1', 'member2', 'member3', 'member4'],
      location: 'CGV 강남',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member3',
      createdAt: now.subtract(const Duration(days: 2)),
    ),
    Event(
      id: 'event_f7',
      familyId: 'family1',
      title: '학부모 상담',
      description: '아들 담임선생님',
      startAt: today.add(const Duration(days: 9, hours: 16)),
      endAt: today.add(const Duration(days: 9, hours: 17)),
      participants: ['member1'],
      location: '학교',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 5)),
    ),
    Event(
      id: 'event_f8',
      familyId: 'family1',
      title: '인테리어 업체 방문',
      description: '거실 리모델링 견적',
      startAt: today.add(const Duration(days: 10, hours: 11)),
      endAt: today.add(const Duration(days: 10, hours: 12)),
      participants: ['member1', 'member2'],
      location: '우리집',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 1)),
    ),
    
    // === 친구 모임 일정 ===
    Event(
      id: 'event_fr1',
      familyId: 'family1',
      title: '동창회 모임',
      description: '고등학교 동창 정기모임',
      startAt: today.add(const Duration(days: 12, hours: 18)),
      endAt: today.add(const Duration(days: 12, hours: 22)),
      participants: ['member1'],
      location: '홍대 음식점',
      calendarGroupId: 'cal_friends',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 14)),
    ),
    Event(
      id: 'event_fr2',
      familyId: 'family1',
      title: '골프 라운딩',
      description: '월례 골프 모임',
      startAt: today.add(const Duration(days: 14, hours: 6)),
      endAt: today.add(const Duration(days: 14, hours: 14)),
      participants: ['member2'],
      location: '안양CC',
      calendarGroupId: 'cal_friends',
      isPersonal: false,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 7)),
    ),
    Event(
      id: 'event_fr3',
      familyId: 'family1',
      title: '독서 모임',
      description: '이번 달 책: 데미안',
      startAt: today.add(const Duration(days: 11, hours: 14)),
      endAt: today.add(const Duration(days: 11, hours: 16)),
      participants: ['member1'],
      location: '스타벅스 강남역점',
      calendarGroupId: 'cal_friends',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 20)),
    ),
    
    // === 오늘 일정 ===
    Event(
      id: 'event_today1',
      familyId: 'family1',
      title: '점심 약속',
      startAt: today.add(const Duration(hours: 12)),
      endAt: today.add(const Duration(hours: 13, minutes: 30)),
      participants: ['member1'],
      location: '회사 근처 식당',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 1)),
    ),
    Event(
      id: 'event_today2',
      familyId: 'family1',
      title: '저녁 준비',
      startAt: today.add(const Duration(hours: 17)),
      endAt: today.add(const Duration(hours: 18, minutes: 30)),
      participants: ['member1', 'member3'],
      location: '집',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(hours: 5)),
    ),
    
    // === 지난 일정 ===
    Event(
      id: 'event_past1',
      familyId: 'family1',
      title: '건강검진',
      startAt: today.subtract(const Duration(days: 3, hours: -9)),
      endAt: today.subtract(const Duration(days: 3, hours: -12)),
      participants: ['member2'],
      location: '삼성병원',
      calendarGroupId: 'cal_personal',
      isPersonal: true,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 10)),
    ),
    Event(
      id: 'event_past2',
      familyId: 'family1',
      title: '결혼기념일 디너',
      startAt: today.subtract(const Duration(days: 5, hours: -19)),
      endAt: today.subtract(const Duration(days: 5, hours: -21)),
      participants: ['member1', 'member2'],
      location: '프렌치 레스토랑',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 20)),
    ),
    Event(
      id: 'event_past3',
      familyId: 'family1',
      title: '가족 나들이',
      description: '서울숲 피크닉',
      startAt: today.subtract(const Duration(days: 7)),
      endAt: today.subtract(const Duration(days: 7)),
      isAllDay: true,
      participants: ['member1', 'member2', 'member3', 'member4'],
      location: '서울숲',
      calendarGroupId: 'cal_family',
      isPersonal: false,
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 14)),
    ),
  ];
});

/// 데모 추억 (12개+)
final demoMemoriesProvider = Provider<List<Memory>>((ref) {
  final now = DateTime.now();
  
  return [
    // 여행
    Memory(
      id: 'memory1',
      familyId: 'family1',
      title: '제주도 가족여행',
      description: '3박 4일 힐링 여행. 성산일출봉에서 본 일출이 정말 아름다웠다!',
      latitude: 33.4996,
      longitude: 126.5312,
      placeName: '제주 성산일출봉',
      category: 'travel',
      date: now.subtract(const Duration(days: 30)),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 30)),
    ),
    Memory(
      id: 'memory2',
      familyId: 'family1',
      title: '부산 해운대',
      description: '여름휴가로 다녀온 부산. 바다가 시원했다!',
      latitude: 35.1587,
      longitude: 129.1604,
      placeName: '해운대 해수욕장',
      category: 'travel',
      date: now.subtract(const Duration(days: 120)),
      photoUrls: [],
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 120)),
    ),
    Memory(
      id: 'memory3',
      familyId: 'family1',
      title: '경주 불국사',
      description: '역사 탐방 여행. 아이들 교육에 좋았다.',
      latitude: 35.7900,
      longitude: 129.3319,
      placeName: '불국사',
      category: 'travel',
      date: now.subtract(const Duration(days: 90)),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 90)),
    ),
    
    // 맛집
    Memory(
      id: 'memory4',
      familyId: 'family1',
      title: '맛있는 브런치',
      description: '주말 브런치 카페. 팬케이크가 정말 맛있었어요!',
      latitude: 37.5172,
      longitude: 127.0473,
      placeName: '카페 드 파리',
      category: 'food',
      date: now.subtract(const Duration(days: 7)),
      photoUrls: [],
      createdBy: 'member3',
      createdAt: now.subtract(const Duration(days: 7)),
    ),
    Memory(
      id: 'memory5',
      familyId: 'family1',
      title: '아빠 생일 저녁',
      description: '이탈리안 레스토랑에서 축하 파티',
      latitude: 37.5012,
      longitude: 127.0396,
      placeName: '라 포레스타',
      category: 'food',
      date: now.subtract(const Duration(days: 60)),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 60)),
    ),
    Memory(
      id: 'memory6',
      familyId: 'family1',
      title: '새로 생긴 맛집 탐방',
      description: '줄서서 먹은 라멘집. 기다린 보람 있었다!',
      latitude: 37.5665,
      longitude: 126.9936,
      placeName: '이치란 라멘 명동점',
      category: 'food',
      date: now.subtract(const Duration(days: 14)),
      photoUrls: [],
      createdBy: 'member3',
      createdAt: now.subtract(const Duration(days: 14)),
    ),
    
    // 일상
    Memory(
      id: 'memory7',
      familyId: 'family1',
      title: '주말 공원 산책',
      description: '날씨 좋은 주말, 온 가족이 공원에서',
      latitude: 37.5443,
      longitude: 127.0374,
      placeName: '서울숲',
      category: 'daily',
      date: now.subtract(const Duration(days: 21)),
      photoUrls: [],
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 21)),
    ),
    Memory(
      id: 'memory8',
      familyId: 'family1',
      title: '동네 카페에서',
      description: '평범한 주말 오후, 커피 한 잔의 여유',
      latitude: 37.5172,
      longitude: 127.0210,
      placeName: '스타벅스 압구정점',
      category: 'daily',
      date: now.subtract(const Duration(days: 3)),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 3)),
    ),
    Memory(
      id: 'memory9',
      familyId: 'family1',
      title: '우리집 거실에서',
      description: '비오는 날 영화 마라톤',
      latitude: 37.5665,
      longitude: 126.9780,
      placeName: '우리집',
      category: 'daily',
      date: now.subtract(const Duration(days: 10)),
      photoUrls: [],
      createdBy: 'member4',
      createdAt: now.subtract(const Duration(days: 10)),
    ),
    
    // 특별한 날
    Memory(
      id: 'memory10',
      familyId: 'family1',
      title: '크리스마스 파티',
      description: '집에서 즐긴 따뜻한 크리스마스 파티 🎄',
      latitude: 37.5665,
      longitude: 126.9780,
      placeName: '우리집',
      category: 'special',
      date: DateTime(now.year - 1, 12, 25),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: DateTime(now.year - 1, 12, 25),
    ),
    Memory(
      id: 'memory11',
      familyId: 'family1',
      title: '딸 피아노 콩쿠르 수상',
      description: '금상 수상! 너무 자랑스러워요 🏆',
      latitude: 37.5796,
      longitude: 126.9770,
      placeName: '세종문화회관',
      category: 'special',
      date: now.subtract(const Duration(days: 45)),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: now.subtract(const Duration(days: 45)),
    ),
    Memory(
      id: 'memory12',
      familyId: 'family1',
      title: '결혼기념일',
      description: '15주년 기념 디너. 앞으로도 함께해요 💕',
      latitude: 37.5233,
      longitude: 127.0474,
      placeName: '파크하얏트 서울',
      category: 'special',
      date: now.subtract(const Duration(days: 75)),
      photoUrls: [],
      createdBy: 'member2',
      createdAt: now.subtract(const Duration(days: 75)),
    ),
    Memory(
      id: 'memory13',
      familyId: 'family1',
      title: '새해 첫날',
      description: '가족과 함께한 해돋이',
      latitude: 35.1595,
      longitude: 129.0712,
      placeName: '해운대 일출',
      category: 'special',
      date: DateTime(now.year, 1, 1),
      photoUrls: [],
      createdBy: 'member1',
      createdAt: DateTime(now.year, 1, 1),
    ),
  ];
});

/// 데모 거래 (25개+)
final demoTransactionsProvider = Provider<List<BudgetTransaction>>((ref) {
  final now = DateTime.now();
  final thisMonth = DateTime(now.year, now.month, 1);
  final lastMonth = DateTime(now.year, now.month - 1, 1);
  
  return [
    // === 수입 ===
    BudgetTransaction(
      id: 'trans_inc1',
      familyId: 'family1',
      type: 'income',
      amount: 5200000,
      category: 'income',
      memo: '아빠 월급',
      date: DateTime(thisMonth.year, thisMonth.month, 25),
      userId: 'member2',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_inc2',
      familyId: 'family1',
      type: 'income',
      amount: 3800000,
      category: 'income',
      memo: '엄마 월급',
      date: DateTime(thisMonth.year, thisMonth.month, 25),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_inc3',
      familyId: 'family1',
      type: 'income',
      amount: 500000,
      category: 'income',
      memo: '부업 수입',
      date: DateTime(thisMonth.year, thisMonth.month, 15),
      userId: 'member1',
      createdAt: now,
    ),
    
    // === 고정 지출 ===
    BudgetTransaction(
      id: 'trans_fix1',
      familyId: 'family1',
      type: 'expense',
      amount: 1500000,
      category: 'housing',
      memo: '월세',
      date: DateTime(thisMonth.year, thisMonth.month, 1),
      userId: 'member1',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_fix2',
      familyId: 'family1',
      type: 'expense',
      amount: 350000,
      category: 'education',
      memo: '딸 피아노 학원',
      date: DateTime(thisMonth.year, thisMonth.month, 5),
      userId: 'member1',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_fix3',
      familyId: 'family1',
      type: 'expense',
      amount: 280000,
      category: 'education',
      memo: '아들 영어 학원',
      date: DateTime(thisMonth.year, thisMonth.month, 5),
      userId: 'member1',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_fix4',
      familyId: 'family1',
      type: 'expense',
      amount: 150000,
      category: 'utilities',
      memo: '인터넷 + TV',
      date: DateTime(thisMonth.year, thisMonth.month, 10),
      userId: 'member2',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_fix5',
      familyId: 'family1',
      type: 'expense',
      amount: 89000,
      category: 'entertainment',
      memo: '넷플릭스 + 스포티파이',
      date: DateTime(thisMonth.year, thisMonth.month, 1),
      userId: 'member3',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_fix6',
      familyId: 'family1',
      type: 'expense',
      amount: 450000,
      category: 'transport',
      memo: '자동차 할부금',
      date: DateTime(thisMonth.year, thisMonth.month, 15),
      userId: 'member2',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now,
    ),
    
    // === 변동 지출 - 식비 ===
    BudgetTransaction(
      id: 'trans_food1',
      familyId: 'family1',
      type: 'expense',
      amount: 387000,
      category: 'food',
      memo: '이마트 장보기',
      date: now.subtract(const Duration(days: 3)),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_food2',
      familyId: 'family1',
      type: 'expense',
      amount: 45000,
      category: 'food',
      memo: '배달 음식 (치킨)',
      date: now.subtract(const Duration(days: 1)),
      userId: 'member3',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_food3',
      familyId: 'family1',
      type: 'expense',
      amount: 156000,
      category: 'food',
      memo: '외식 - 가족 저녁',
      date: now.subtract(const Duration(days: 5)),
      userId: 'member2',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_food4',
      familyId: 'family1',
      type: 'expense',
      amount: 23000,
      category: 'food',
      memo: '편의점',
      date: now.subtract(const Duration(days: 2)),
      userId: 'member4',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_food5',
      familyId: 'family1',
      type: 'expense',
      amount: 89000,
      category: 'food',
      memo: '온라인 식재료 주문',
      date: now.subtract(const Duration(days: 7)),
      userId: 'member1',
      createdAt: now,
    ),
    
    // === 변동 지출 - 교통 ===
    BudgetTransaction(
      id: 'trans_trans1',
      familyId: 'family1',
      type: 'expense',
      amount: 85000,
      category: 'transport',
      memo: '주유비',
      date: now.subtract(const Duration(days: 4)),
      userId: 'member2',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_trans2',
      familyId: 'family1',
      type: 'expense',
      amount: 50000,
      category: 'transport',
      memo: '교통카드 충전',
      date: now.subtract(const Duration(days: 10)),
      userId: 'member1',
      createdAt: now,
    ),
    
    // === 변동 지출 - 쇼핑 ===
    BudgetTransaction(
      id: 'trans_shop1',
      familyId: 'family1',
      type: 'expense',
      amount: 129000,
      category: 'shopping',
      memo: '아들 운동화',
      date: now.subtract(const Duration(days: 8)),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_shop2',
      familyId: 'family1',
      type: 'expense',
      amount: 45000,
      category: 'shopping',
      memo: '생활용품 (쿠팡)',
      date: now.subtract(const Duration(days: 6)),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_shop3',
      familyId: 'family1',
      type: 'expense',
      amount: 78000,
      category: 'shopping',
      memo: '아이들 문구류',
      date: now.subtract(const Duration(days: 12)),
      userId: 'member1',
      createdAt: now,
    ),
    
    // === 변동 지출 - 여가 ===
    BudgetTransaction(
      id: 'trans_ent1',
      familyId: 'family1',
      type: 'expense',
      amount: 56000,
      category: 'entertainment',
      memo: '영화 관람 (4명)',
      date: now.subtract(const Duration(days: 2)),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_ent2',
      familyId: 'family1',
      type: 'expense',
      amount: 35000,
      category: 'entertainment',
      memo: '볼링장',
      date: now.subtract(const Duration(days: 9)),
      userId: 'member2',
      createdAt: now,
    ),
    
    // === 변동 지출 - 건강 ===
    BudgetTransaction(
      id: 'trans_health1',
      familyId: 'family1',
      type: 'expense',
      amount: 45000,
      category: 'health',
      memo: '약국 - 감기약',
      date: now.subtract(const Duration(days: 5)),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_health2',
      familyId: 'family1',
      type: 'expense',
      amount: 120000,
      category: 'health',
      memo: '병원 진료비',
      date: now.subtract(const Duration(days: 11)),
      userId: 'member4',
      createdAt: now,
    ),
    
    // === 공과금 ===
    BudgetTransaction(
      id: 'trans_util1',
      familyId: 'family1',
      type: 'expense',
      amount: 89000,
      category: 'utilities',
      memo: '전기세',
      date: DateTime(thisMonth.year, thisMonth.month, 20),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_util2',
      familyId: 'family1',
      type: 'expense',
      amount: 35000,
      category: 'utilities',
      memo: '수도세',
      date: DateTime(thisMonth.year, thisMonth.month, 20),
      userId: 'member1',
      createdAt: now,
    ),
    BudgetTransaction(
      id: 'trans_util3',
      familyId: 'family1',
      type: 'expense',
      amount: 67000,
      category: 'utilities',
      memo: '가스비',
      date: DateTime(thisMonth.year, thisMonth.month, 20),
      userId: 'member1',
      createdAt: now,
    ),
    
    // === 지난 달 거래 (일부) ===
    BudgetTransaction(
      id: 'trans_last1',
      familyId: 'family1',
      type: 'income',
      amount: 5200000,
      category: 'income',
      memo: '아빠 월급',
      date: DateTime(lastMonth.year, lastMonth.month, 25),
      userId: 'member2',
      createdAt: now.subtract(const Duration(days: 30)),
    ),
    BudgetTransaction(
      id: 'trans_last2',
      familyId: 'family1',
      type: 'expense',
      amount: 1500000,
      category: 'housing',
      memo: '월세',
      date: DateTime(lastMonth.year, lastMonth.month, 1),
      userId: 'member1',
      isRecurring: true,
      recurringType: 'monthly',
      createdAt: now.subtract(const Duration(days: 30)),
    ),
  ];
});

/// 데모 채팅 메시지 (10개+)
final demoChatMessagesProvider = Provider<List<ChatMessage>>((ref) {
  final now = DateTime.now();

  return [
    ChatMessage(
      id: 'chat1',
      familyId: 'family1',
      senderId: 'member1',
      senderName: '엄마',
      content: '오늘 저녁 뭐 먹을까요?',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 3)),
      readBy: ['member1', 'member2', 'member3', 'member4'],
    ),
    ChatMessage(
      id: 'chat2',
      familyId: 'family1',
      senderId: 'member3',
      senderName: '큰딸',
      content: '파스타 어때요?',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 2, minutes: 50)),
      readBy: ['member1', 'member2', 'member3', 'member4'],
    ),
    ChatMessage(
      id: 'chat3',
      familyId: 'family1',
      senderId: 'member4',
      senderName: '아들',
      content: '저도 파스타 좋아요!',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 2, minutes: 45)),
      readBy: ['member1', 'member2', 'member3', 'member4'],
    ),
    ChatMessage(
      id: 'chat4',
      familyId: 'family1',
      senderId: 'member2',
      senderName: '아빠',
      content: '나도 찬성! 오늘 퇴근 좀 늦을 것 같아요. 7시쯤 갈게요.',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 2, minutes: 30)),
      readBy: ['member1', 'member2', 'member3', 'member4'],
    ),
    ChatMessage(
      id: 'chat5',
      familyId: 'family1',
      senderId: 'member1',
      senderName: '엄마',
      content: '알겠어요~ 그럼 파스타로 할게요. 마트 갔다 올게!',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 2, minutes: 20)),
      readBy: ['member1', 'member2', 'member3', 'member4'],
    ),
    ChatMessage(
      id: 'chat6',
      familyId: 'family1',
      senderId: 'member3',
      senderName: '큰딸',
      content: '엄마 저 피아노 학원 끝나고 갈게요!',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 1, minutes: 30)),
      readBy: ['member1', 'member3'],
    ),
    ChatMessage(
      id: 'chat7',
      familyId: 'family1',
      senderId: 'member1',
      senderName: '엄마',
      content: '응 알겠어~ 조심히 와!',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(hours: 1, minutes: 25)),
      readBy: ['member1', 'member3'],
    ),
    ChatMessage(
      id: 'chat8',
      familyId: 'family1',
      senderId: 'member4',
      senderName: '아들',
      content: '숙제 다 했어요!',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(minutes: 45)),
      readBy: ['member1', 'member4'],
    ),
    ChatMessage(
      id: 'chat9',
      familyId: 'family1',
      senderId: 'member1',
      senderName: '엄마',
      content: '잘했어~ 조금 있다 밥 먹자',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(minutes: 40)),
      readBy: ['member1', 'member4'],
    ),
    ChatMessage(
      id: 'chat10',
      familyId: 'family1',
      senderId: 'member2',
      senderName: '아빠',
      content: '지금 출발해요! 곧 도착할게요',
      type: MessageType.text,
      createdAt: now.subtract(const Duration(minutes: 15)),
      readBy: ['member1', 'member2'],
    ),
  ];
});

/// 데모 메모 카테고리 (4개)
final demoMemoCategoriesProvider = Provider<List<MemoCategory>>((ref) {
  final now = DateTime.now();
  return [
    MemoCategory(
      id: 'diary',
      userId: 'user1',
      name: '일기',
      icon: 'book_1',
      color: '#FFB74D',
      sortOrder: 0,
      createdAt: now,
    ),
    MemoCategory(
      id: 'note',
      userId: 'user1',
      name: '간단메모',
      icon: 'note_1',
      color: '#64B5F6',
      sortOrder: 1,
      createdAt: now,
    ),
    MemoCategory(
      id: 'idea',
      userId: 'user1',
      name: '아이디어',
      icon: 'lamp_charge',
      color: '#BA68C8',
      sortOrder: 2,
      createdAt: now,
    ),
    MemoCategory(
      id: 'todo_memo',
      userId: 'user1',
      name: '할일메모',
      icon: 'task_square',
      color: '#4DB6AC',
      sortOrder: 3,
      createdAt: now,
    ),
  ];
});

/// 데모 메모 (10개+)
final demoMemosProvider = Provider<List<Memo>>((ref) {
  final now = DateTime.now();

  return [
    // 고정 메모
    Memo(
      id: 'memo1',
      userId: 'user1',
      title: '가족 비상연락처',
      content: '''아빠 회사: 02-1234-5678
엄마 회사: 02-8765-4321
할머니: 010-1111-2222
할아버지: 010-3333-4444
가까운 병원: 강남세브란스 02-2019-3114''',
      categoryId: 'note',
      categoryName: '간단메모',
      tags: ['중요', '연락처'],
      isPinned: true,
      createdAt: now.subtract(const Duration(days: 30)),
      updatedAt: now.subtract(const Duration(days: 5)),
      createdBy: 'member1',
    ),
    Memo(
      id: 'memo2',
      userId: 'user1',
      title: 'Wi-Fi 비밀번호',
      content: '''거실 공유기: family2024!
서재 공유기: study_room123
게스트용: guest1234''',
      categoryId: 'note',
      categoryName: '간단메모',
      tags: ['집', '비밀번호'],
      isPinned: true,
      createdAt: now.subtract(const Duration(days: 60)),
      updatedAt: now.subtract(const Duration(days: 60)),
      createdBy: 'member2',
    ),

    // 일기
    Memo(
      id: 'memo3',
      userId: 'user1',
      title: '',
      content: '''오늘 딸이 피아노 학원에서 상을 받아왔다. 그동안 매일 연습하느라 힘들었을 텐데 정말 대견하다. 저녁에 치킨 시켜서 축하해줬더니 정말 좋아했다.

아이들이 자라는 모습을 보면서 뿌듯함을 느낀다. 앞으로도 열심히 응원해줘야지.''',
      categoryId: 'diary',
      categoryName: '일기',
      tags: ['육아', '행복'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 3)),
      updatedAt: now.subtract(const Duration(days: 3)),
      createdBy: 'member1',
    ),
    Memo(
      id: 'memo4',
      userId: 'user1',
      title: '주말 가족 나들이',
      content: '''서울숲에서 피크닉을 했다. 날씨가 정말 좋았고, 아이들이 자전거 타면서 신나했다.

도시락은 김밥이랑 샌드위치를 준비했는데 다 먹었다. 다음에는 삼겹살 구워먹자는 아빠 의견.''',
      categoryId: 'diary',
      categoryName: '일기',
      tags: ['가족', '나들이'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 7)),
      updatedAt: now.subtract(const Duration(days: 7)),
      createdBy: 'member1',
    ),

    // 아이디어
    Memo(
      id: 'memo5',
      userId: 'user1',
      title: '여름 휴가 계획',
      content: '''후보지:
1. 제주도 - 항공권 예약 필요, 렌터카 필수
2. 부산 해운대 - KTX로 이동, 호텔 예약
3. 강릉 - 드라이브 여행, 펜션

예산: 150만원 정도
기간: 3박 4일

아이들 방학 맞춰서 7월 말~8월 초가 좋을 듯''',
      categoryId: 'idea',
      categoryName: '아이디어',
      tags: ['여행', '계획'],
      isPinned: false,
      aiAnalysis: '가족 여름 휴가 계획입니다. 제주도, 부산, 강릉 세 곳을 후보로 두고 계시네요. 예산과 기간을 고려하면 KTX로 이동 가능한 부산이 이동 시간 대비 효율적일 수 있습니다.',
      analyzedAt: now.subtract(const Duration(days: 1)),
      createdAt: now.subtract(const Duration(days: 14)),
      updatedAt: now.subtract(const Duration(days: 1)),
      createdBy: 'member1',
    ),
    Memo(
      id: 'memo6',
      userId: 'user1',
      title: '거실 인테리어 아이디어',
      content: '''- 소파 교체 (그레이 패브릭)
- 러그 추가 (160x230)
- 조명 교체 (간접조명)
- 벽면 갤러리 월 만들기
- 식물 추가 (몬스테라, 여행자나무)

예산: 300만원 내외
참고: 오늘의집 앱 스크랩 참고''',
      categoryId: 'idea',
      categoryName: '아이디어',
      tags: ['인테리어', '집'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 10)),
      updatedAt: now.subtract(const Duration(days: 10)),
      createdBy: 'member1',
    ),

    // 할일메모
    Memo(
      id: 'memo7',
      userId: 'user1',
      title: '이번 주 장볼 것',
      content: '''식재료:
- 우유 2팩
- 계란 30구
- 돼지고기 (삼겹살, 목살)
- 소고기 (국거리용)
- 두부, 콩나물
- 양파, 대파, 마늘

생필품:
- 휴지 (30롤)
- 세제
- 샴푸''',
      categoryId: 'todo_memo',
      categoryName: '할일메모',
      tags: ['장보기'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now.subtract(const Duration(days: 1)),
      createdBy: 'member1',
    ),
    Memo(
      id: 'memo8',
      userId: 'user1',
      title: '아들 생일파티 준비',
      content: '''날짜: 다음 주 토요일
장소: 집

준비물:
- 케이크 주문 (초코케이크)
- 풍선, 가랜드
- 간식 (피자, 치킨 주문)
- 선물 포장

초대: 5명 정도
예산: 30만원''',
      categoryId: 'todo_memo',
      categoryName: '할일메모',
      tags: ['생일', '파티'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 5)),
      updatedAt: now.subtract(const Duration(days: 4)),
      createdBy: 'member1',
    ),

    // 간단메모
    Memo(
      id: 'memo9',
      userId: 'user1',
      title: '택배 송장번호',
      content: '''쿠팡 - 123456789012
네이버 - 987654321098

둘 다 이번 주 중 도착 예정''',
      categoryId: 'note',
      categoryName: '간단메모',
      tags: ['택배'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 1)),
      updatedAt: now.subtract(const Duration(days: 1)),
      createdBy: 'member2',
    ),
    Memo(
      id: 'memo10',
      userId: 'user1',
      title: '읽고 싶은 책',
      content: '''1. 원씽 - 게리 켈러
2. 아주 작은 습관의 힘 - 제임스 클리어
3. 부의 추월차선 - 엠제이 드마코
4. 역행자 - 자청''',
      categoryId: 'note',
      categoryName: '간단메모',
      tags: ['독서', '자기계발'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 20)),
      updatedAt: now.subtract(const Duration(days: 20)),
      createdBy: 'member3',
    ),
    Memo(
      id: 'memo11',
      userId: 'user1',
      title: '',
      content: '''오늘 학교에서 발표를 잘했다!
선생님이 칭찬해주셨다.
다음에도 열심히 해야지.''',
      categoryId: 'diary',
      categoryName: '일기',
      tags: ['학교'],
      isPinned: false,
      createdAt: now.subtract(const Duration(days: 2)),
      updatedAt: now.subtract(const Duration(days: 2)),
      createdBy: 'member4',
    ),
  ];
});
